name: Use Metadata + Changelog

on: push

jobs:
  metadata:
    uses: Boomchainlab/.github/.github/workflows/set-build-metadata.yml@main

  deploy:
    needs: metadata
    runs-on: ubuntu-latest
    steps:
      - name: Download build assets
        uses: actions/download-artifact@v4
        with:
          name: build-assets

      - name: View metadata and changelog
        run: |
          cat metadata.env
          echo "---"
          cat CHANGELOG.md
